language: node_js
script:
  - npm install
deploy:
  provider: heroku
  api_key:
    secure: RLoClzj1YQ/WhBZqQVG7krzOcFYGQjw5Xw/e1nWvx4AzdcDEOWpv7gWRzfLvxnK39kCE9awIHXjigEHqacq8SUbtTSuRFVMbvegS3qyRj0uXLYz4lkDZAIt4oVNzNhnS9bhYvzsEdwl9b4nyX9fbbP9yMyO7mMurF1e9XnkGqRcSZnr2yopDCTEra68u24ebm1TJpWFjfQa9fhbnK9h6oM5AVKT8zq9jAcMON1bqG//K0GERlLZ8Y4KeE8VLV9oky0itTqMwpqszd6Km2TGjSfKJ+eaujhBdGck/c7x8vPIziYexrYuAkIhfHKIIS6pWFpiNSHPAKqC3Ra773wEHE2ouVdpfPHzvbkL63oSNLKzDlcRXeSmAdisZOvCz9lt71BnFr/O296JxRx2Fo0TorTDk1N2Xo8uuPZVucBmyeddp1D4/VcXdowxGm1fnUuBn/KBkDOP3xbSryP2dNRdd8KV8aq/loN7ZdRIOQq2ky9xj8Z1PkXJV6JJ8QvFMMWxvqPaXReysiAd4nOhT1BBjYU+RysJwzVca5b9k4ZH/zb8cvW7SJ0MwskHn6Z5gPyvpnzYnUjC3hexCLOdUV2/G/88C/VCIZ5x1vf32jrBk7AcRjmVvTH4rZzP9saG1+KpwZjw9OKJyPQpgvSnxgOSjKnFv35oN+EwI+lbD2/fM5jc=
  app: movie-db-angular
  on:
    repo: garethdn/MovieDbAngular
  skip_cleanup: true
notifications:
  email:
    on_success: always
    on_failure: always